#!/bin/bash
function helper {
echo "Generating uuid list in $1"
echo "
Press Ctrl+C to stop generating list"
i=0
while i=o; do
	echo `uuidgen` >> $1
done
}

if [ "$1" = "" ]; then
        echo "Where would you like to store uuid list?"
        read INPUT
	helper $INPUT
else
	helper $1
fi
